# Load Fish
set -g default-shell /usr/bin/fish
set -g default-command /usr/bin/fish

# Enable Mouse Mode
set -g mouse on

# Ctrl+a for Prefix & Double Ctrl+a for Inner tmux Passthrough
unbind C-b
set-option -g prefix C-a
bind C-a send-prefix

# Reload file with 'r'
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# Vim keys to change panes
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D

# Alt + Shift + _/= to split
bind -n M-+ split-window -h -c "#{pane_current_path}"
bind -n M-_ split-window -v -c "#{pane_current_path}"

# Ctrl+a + b toggles tmux bar
bind-key b set-option -g status

# F5 Toggles Local tmux Off / On
bind -n F5 \
  set key-table off \;\
  set prefix None \;\
  set status-style "bg=#24283b,fg=#565f89" \;\
  refresh-client -S

bind -T off F5 \
  set -u key-table \;\
  set -u prefix \;\
  set -u status-style \;\
  refresh-client -S

# Colour
set -g status-style "bg=#1a1b26,fg=#e0af68"
